### ISSUE TITLE
Add more information to train numbers

### ISSUE THREAD

**Issue by Chamaeleon-** [PKuebler/bahn-bot#13]
I get this dialogue for IC 147, there are currently two of them:
![image](https://user-images.githubusercontent.com/5526614/89551709-8a9ce780-d80b-11ea-97f6-d97257678f72.jpeg)
Can you add more information to the buttons? 
On `marudor.de` the train list also displays the destination:
![image](https://user-images.githubusercontent.com/5526614/89552015-e5364380-d80b-11ea-82bd-5aa5050abb4f.jpeg)

**Comment by PKuebler** [comment]
good idea. i will try to include it this weekend. i hope it fits on the iphone buttons but the start will be better than nothing.

**Comment by PKuebler** [comment]
Can you test if it works better now? But it should only work with new alarms. With old ones the destination is empty, because the destination is saved when you create it.

**Comment by Chamaeleon-** [comment]
Looks great!
This sample fits on iPhone SE but there may be longer town names. 
![image](https://user-images.githubusercontent.com/5526614/89776524-5fb3db80-db0a-11ea-8fba-edf4e02c5133.jpeg)

**Comment by PKuebler** [comment]
thanks for your feedback :)
