### ISSUE TITLE
UI: change Bot buttons

### ISSUE THREAD

**Issue by Chamaeleon-** [PKuebler/bahn-bot#8]
The current buttons aren't readable on smaller smartphones (iPhone SE 1).
![image](https://user-images.githubusercontent.com/5526614/89397040-a327d780-d70f-11ea-9595-a6b0652579ae.jpeg)
![image](https://user-images.githubusercontent.com/5526614/89397055-a6bb5e80-d70f-11ea-940b-db95574b6d6f.jpeg)

They could be changed to vertically stacking buttons.

**Comment by PKuebler** [comment]
@Chamaeleon- all buttons are now always in a new line. can you test it again?

**Comment by Chamaeleon-** [comment]
Looks great:
![image](https://user-images.githubusercontent.com/5526614/89551533-59241c00-d80b-11ea-977d-392d3e00930a.jpeg)
