### ISSUE TITLE
Feature request: shortcut to set alarm

### ISSUE THREAD

**Issue by Chamaeleon-** [PKuebler/bahn-bot#9]
It would be nice to be able to set an alarm with `/newalarm IC2443` as a shortcut.

Currently the bot ignores input after `/newalarm`:
![image](https://user-images.githubusercontent.com/5526614/89397809-98217700-d710-11ea-9c74-da1e7212fc1f.jpeg)

**Comment by PKuebler** [comment]
@Chamaeleon- very cool idea. i put it in and it should work.

**Comment by Chamaeleon-** [comment]
Yay, it works \o/
